name: dart_tolk
description: Dart bindings for the Tolk screen reader library.
version: 1.2.0
homepage: https://github.com/chrisnorman7/dart_tolk

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  ffigen: ^4.1.2
  lints: ^1.0.1
  test: ^1.19.5

ffigen:
  output: "lib/tolk_bindings.dart"
  name: "DartTolk"
  description: "Bindings for the Tolk screen reader library"
  headers:
    entry-points:
      - "tolk/src/tolk.h"
