name: dart_tolk
description: Dart bindings for the Tolk screen reader library.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi:

dev_dependencies:
  ffigen:
  pedantic:
  test:

ffigen:
  output: "lib/tolk_bindings.dart"
  name: "DartTolk"
  description: "Bindings for the Tolk screen reader library"
  headers:
    entry-points:
      - "tolk/src/tolk.h"
