name: dart_tolk
version: 1.4.0
description: Dart bindings for the Tolk screen reader library.
homepage: https://github.com/chrisnorman7/dart_tolk

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  ffigen: ^6.0.1
  lints: ^2.0.0

ffigen:
  output: "lib/tolk_bindings.dart"
  name: "DartTolk"
  description: "Bindings for the Tolk screen reader library"
  headers:
    entry-points:
      - "tolk/src/tolk.h"
      - "tolk/src/tolkVersion.h"
  functions:
    include:
      - "Tolk_.*"
